# Generated by Django 5.0.4 on 2024-05-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='text3dmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='text3dmodel',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stl_files/'),
        ),
        migrations.AlterField(
            model_name='text3dmodel',
            name='font_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='text3dmodel',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='text3dmodel',
            name='font',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.font'),
            preserve_default=False,
        ),
    ]
