# Generated by Django 5.0.4 on 2024-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_font_remove_text3dmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text3dmodel',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stlfiles/'),
        ),
    ]
